### ISSUE TITLE
Feat: To create logic for  sign up and login form 

### ISSUE THREAD

**Issue by DhairyaMajmudar** [IIITians-Network-23/IIITiansNetwork#16]
To develop the logic for the sign up and the login form. ( When to show which form )

**Comment by zakhaev26** [comment]
Hey @DhairyaMajmudar , I want to work on this.

**Comment by DhairyaMajmudar** [comment]
Sure assigning this issue to you @zakhaev26 
You can take ref. from this  https://nextjs.org/learn

**Comment by yogeyyy** [comment]
I am taking this issue.

**Comment by DhairyaMajmudar** [comment]
> I am taking this issue.

Sure @yogeyyy go ahead 🚀

**Comment by yogeyyy** [comment]
This issue is resolved already.
