### ISSUE TITLE
Feat: Create Navbar

### ISSUE THREAD

**Issue by DhairyaMajmudar** [IIITians-Network-23/IIITiansNetwork#3]
To create the navbar of the official Website of IIITians Network 
Developer can take reference from the below figma link given in below    

[Figma Design](https://github.com/IIITians-Network-23/IIITiansNetwork/issues/2)

**Comment by CoderKaushik** [comment]
Hey @DhairyaMajmudar, I'd like to work on this issue.

**Comment by DhairyaMajmudar** [comment]
> Hey @DhairyaMajmudar, I'd like to work on this issue.

Thanks for showing your interest @CoderKaushik PR related ti this issue is already opened pls. take a look at another issues
