### ISSUE TITLE
Feat: To create the SignIn Page

### ISSUE THREAD

**Issue by DhairyaMajmudar** [IIITians-Network-23/IIITiansNetwork#6]
To create the SignIn Page of the official Website of IIITians Network 
Developer can take reference from the below figma link given in below    

[Figma Design](https://github.com/IIITians-Network-23/IIITiansNetwork/issues/2)

**Comment by hariFED** [comment]
Happy to work on this work. Need more info about the tech stack used and the design for the "Sign In" section @DhairyaMajmudar .

**Comment by DhairyaMajmudar** [comment]
> Happy to work on this work. Need more info about the tech stack used and the design for the "Sign In" section @DhairyaMajmudar .

Thank you for showing your interest @hariFED But implementation of these features will be done by Technical Team of IIITians Network. Pls. look for any other issues.

**Comment by DhairyaMajmudar** [comment]
Taking up this issue @yogeyyy
